version: '3'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: limbic_therapist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis cache
  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"

  # Node.js application
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - HTTP_PORT=3000
      - DATABASE_URL=postgres://postgres:password@postgres:5432/limbic_therapist
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"

volumes:
  postgres_data:
    driver: local
